/* CH32V003 */
MEMORY
{
    /* Code Flash, 16KB max */
	FLASH : ORIGIN = 0x08000000, LENGTH = 16k
    /* SRAM, 2KB max */
	RAM : ORIGIN = 0x20000000, LENGTH = 4k
}

REGION_ALIAS("REGION_TEXT", FLASH);
REGION_ALIAS("REGION_RODATA", FLASH);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);

